## Data Analysis with Numpy, Pandas, Matplotlib and Seaborn

#### Data Analysis 

This is the process of inspecting, cleaning, transforming and modelling data.


#### Numpy

numpy which stands for numerical python is a an open source mathematical and scientific library for python programming tasks. it offers a collection of high-level mathematical functions including support for multi-dimensional arrays, masked arrays and matrices. 
cc:techtarget.com
in other to use the numpy library you will always have to import it 

In [1]:
import numpy as np
import numpy

In [2]:
x = numpy.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

#### Creating an Array

In [3]:
x = np.array([1, 2, 3, 4.5, 5])
x

array([1. , 2. , 3. , 4.5, 5. ])

#### slicing and indexing arrays

#### indexing

In [4]:
x[-1]

np.float64(5.0)

In [5]:
x.ndim

1

In [6]:
x[0]

np.float64(1.0)

#### Slicing

In [7]:
x[:2]

array([1., 2.])

In [8]:
x[2:]

array([3. , 4.5, 5. ])

#### Numpy types

In [9]:
x.dtype

dtype('float64')

#### Dimension and shape of Matrices

In [10]:
a = np.arange(1,10,).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.shape

(3, 3)

In [12]:
a.size

9

In [13]:
a.ndim

2

#### indexing

In [14]:
a[1]

array([4, 5, 6])

In [15]:
a[1,0]

np.int64(4)

#### Slicing

In [16]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[:2, 2:]

array([[3],
       [6]])

#### Summary Statistics
##### Arrays

In [18]:
l = np.array([1, 2, 3, 4])
l

array([1, 2, 3, 4])

In [19]:
l.sum()

np.int64(10)

In [20]:
l.mean()

np.float64(2.5)

In [21]:
l.std()

np.float64(1.118033988749895)

In [22]:
l.var()

np.float64(1.25)

#### Matrices

In [23]:
k = np.arange(9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
k.sum()
k.sum(axis = 0)
k.sum(axis = 1)

array([ 3, 12, 21])

In [25]:
k.sum(axis = 0)

array([ 9, 12, 15])

In [26]:
k.mean()
k.mean(axis = 0)
k.mean(axis = 1)

array([1., 4., 7.])

In [27]:
k.std()
k.std(axis = 0)
k.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

In [28]:
k.var()
k.var(axis = 0)
k.var(axis = 1)

array([0.66666667, 0.66666667, 0.66666667])